### PR TITLE
Fixed "Enum.into" warning

### PR DESCRIPTION
**Pull request by vemperor**
Warning introduced in Elixir 1.8.0.

Please review this PR, I'm unsure about my code (didn't trace the whole project, sorry). Tests pass, so it should work.

### CODE REVIEW

**Comment by jsonkenl** [comment]
Thanks for the fix @vemperor!

**Comment by junjizhi** [comment]
@jsonkenl can you publish a new hex package to remove this warning? It's been a bit annoying to see those messages. thanks

**Comment by jsonkenl** [comment]
@junjizhi Published...sorry for the delay, I'm a tax professional by day and so I've been slammed with my busy season. If you have further issues, please let me know.

**Comment by junjizhi** [comment]
@jsonkenl Thank you for your work on maintaining this repo! Wish you all the best.

**Pull request merged**
